### ISSUE TITLE
Deploy artifact to Maven repository

### ISSUE THREAD

**Issue by guusdk** [jitsi/jitsi-videobridge-openfire-plugin#1]
The Maven artifact that is generated from this project should (automatically) be deployed to the Jitsi maven repository.

Note that maven artifact is `target/jitsi-videobridge-openfire-<version>.jar`, not `target/jitsivideobridge.jar` (which is another jar in a specific Openfire plugin structure).

**Comment by damencho** [comment]
Who will be consuming this artefact?

**Comment by guusdk** [comment]
I already am (but need to build them locally, which is a drag)

**Comment by damencho** [comment]
Nope, I mean is there a project referencing it? 
Why do we need to upload it to the repo if no one is referencing it?

**Comment by guusdk** [comment]
That is what I ment too. Here:
https://github.com/igniterealtime/community-plugins/blob/ofmeet-version-0.4.x/ofmeet/pom.xml

**Comment by damencho** [comment]
Ahaaa got it :) Will try to do it these days, but we have a long weekend ...

**Comment by guusdk** [comment]
Tx!

**Comment by ndandanov** [comment]
Hi, I am also interested in using the artefact :)
@guusdk, could you please share how you do the builds manually? I think this would be a nice temporary workaround. 

Thank you!
Nikolay

**Comment by guusdk** [comment]
It's a standard Maven project, which you should be able to build and install in your local repository in this way:

    mvn clean install

**Comment by damencho** [comment]
There is a jenkins task now that will be kicked as long there is a change (checks every 5 minutes) in the plugin and will upload the plugin maven artefact to jitsi-meet-maven-repository.

**Comment by guusdk** [comment]
Verified! After a merge, this got updated automatically: https://github.com/jitsi/jitsi-maven-repository/tree/master/snapshots/org/jitsi/jitsi-videobridge-openfire/

Thanks!
