### ISSUE TITLE
Make plugin available for download

### ISSUE THREAD

**Issue by guusdk** [jitsi/jitsi-videobridge-openfire-plugin#2]
The Openfire plugin that is generated from this project should be made available for download - for instance at https://download.jitsi.org/jitsi-videobridge/openfire/

Note that the Openfire plugin is `target/jitsivideobridge.jar`, not `target/jitsi-videobridge-openfire-<version>.jar` (which is the regular Maven JAR artifact, containing the compiled java sources which are not in the Openfire plugin structure).

**Comment by damencho** [comment]
There is a jenkins task now that will be kicked as long there is a change in the plugin (checks every 5 minutes) and will upload the plugin to the download location.

**Comment by guusdk** [comment]
I've just verified that it works: after merging something, a new build popped up here: https://download.jitsi.org/jitsi-videobridge/openfire/

However, the version numbering seems to have restarted, while there are still some old (higher) version numbers in the directory. Perhaps we should remove those now (or rename them). People looking at the version number will download the highest number, expecting the latest code, but getting really old code. Also, at some point, the version numbers will clash - not sure what happens then.

**Comment by damencho** [comment]
Ok, I will now remove the old ones. This plugin has now its own build number as its a different job.
