### ISSUE TITLE
Enable continuous integration

### ISSUE THREAD

**Issue by guusdk** [jitsi/jitsi-videobridge-openfire-plugin#4]
The standards set of checks that are applied to PRs on Jitsi repositories should be enabled (contributor agreement, CI builds, etc). This appears to be missing, judging from this test PR that I did just now: https://github.com/jitsi/jitsi-videobridge-openfire-plugin/pull/3

**Comment by damencho** [comment]
For those repos where there is no PR testing, there are no contributer agreement, its the PR testing plugin that comments.
And here we don't have any tests so this will not be enabled. If you want you can add some md, or text in the readme or PR template that has some hint about it.
Building and uploading the plugin will be added.

**Comment by guusdk** [comment]
I'm not quite sure what you mean, but if you tell me that most of the standard checks are not needed, I'm inclined to believe you. :) Thanks!

**Comment by damencho** [comment]
So for the PR testing of jitsi-meet, lib-jitsi-meet, jicofo and jvb: we check out the latest version of all and the branch for the PR and set up an environment in which jitsi-meet-torture tests are run. This is how it works. 
In the context of this plugin, currently, there is nothing we can do. 
The thing that we can do is setup another machine which will run an openfire installing this plugin and run the torture against it, but we do not have resources currently to do that.

**Comment by guusdk** [comment]
Oh, I don't mind not running tests - I was thinking more of the contributor agreement that's enforced for other repositories. But as I said, if you're happy to go without it, so am I.

**Comment by damencho** [comment]
I was thinking about this approach, that you can just add a PR template adding the CLA text there:
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
So everybody creating a PR will see it.

**Comment by guusdk** [comment]
Sure, works for me. Do you have the text somewhere? Feel free to add it
yourself.
